### ISSUE TITLE
Environment variables in settings.py

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-lti-provider-docker#1]
Is there a reason you run `sed` on settings.py to insert environment variables, instead of reading them from `os.environ`? String replacement makes me uneasy.

https://github.com/numbas/numbas-lti-provider-docker/blob/89f6954f27ded9af7e708d4c66085de8ba1d09ec/files/numbas-lti-provider/entrypoint.sh#L9

**Comment by georgestagg** [comment]
Good idea. No reason other than I didn't think. Probably we can get rid of the secret key being replaced too by writing it to a file on the first run of the docker entry point and reading the file in settings.py

**Comment by christianp** [comment]
ahh, rats, I pushed to main instead of a branch. Sorry!

**Comment by georgestagg** [comment]
You rewrote `settings.env` too 😉. We should probably do something with that anyway. Possibly make what's there a `.dist` and add it to `.gitignore`. I'll take a look tomorrow.
